### ISSUE TITLE
Panic with multiple reexports and namespace

### ISSUE THREAD

**Issue by EdJoPaTo** [denoland/deno_graph#351]
`deno doc` panics with multiple reexports and namespace.

### Minimal Example Code

a.ts

```ts
export * from "./b.ts";
```

b.ts

```ts
export * from "./c.ts";
```

c.ts

```ts
export declare namespace MessageEntity {
  export interface TextLinkMessageEntity {
    type: "text_link";
  }
}
```

main.ts

```ts
// import type { MessageEntity } from 'https://deno.land/x/grammy@v1.19.2/types.ts';
import type { MessageEntity } from "./a.ts";
export type UrlMessageEntity = MessageEntity.TextLinkMessageEntity;
```

Importing `b.ts` works fine. Omitting the namespace also works fine. So they seem to relevant and can not be removed from this minimal example.

```plaintext
$ RUST_BACKTRACE=1 deno doc main.ts

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.39.2
Args: ["deno", "doc", "main.ts"]

thread 'main' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_graph-0.62.2/src/symbols/cross_module.rs:629:60:
called `Option::unwrap()` on a `None` value
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The [mentioned line](https://github.com/denoland/deno_graph/blob/5a1146f4014f7a2a6819b648869870150de5b5d8/src/symbols/cross_module.rs#L629) is still the same in the current main branch so updating to its new release from a few hours ago will not fix this.

### reexport creates another panic

Funnily changing to a reexport creates a panic in the `deno_doc` crate and not anymore in `deno_graph`.

main.ts

```ts
export type { MessageEntity } from "./a.ts";
```

```plaintext
$ RUST_BACKTRACE=1 deno doc main.ts

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.39.2
Args: ["deno", "doc", "main.ts"]

thread 'main' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_doc-0.85.0/src/visibility.rs:212:66:
called `Option::unwrap()` on a `None` value
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Again changing to `b.ts` works fine so the deep reexport is required.

The mentioned code line still exists on a different line number on the current main: https://github.com/denoland/deno_doc/blob/0cd916e066edba623c809a3d16a3144d5d07200d/src/visibility.rs#L221

Should I also create an issue in the `deno_doc` repo?

**Comment by dsherret** [comment]
Thanks for the report and simple reproduction!
